[package]
name = "chip-8_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
num = "0.4.0"
sdl2 = "0.35.2"
substring = "1.4.5"
